version: '3'

volumes:
  mongodb_data:
    driver: local

services:
  app:
    image: docker.pkg.github.com/dylanblokhuis/twitch-emotes-warehouse/app:latest
    ports:
      - 80:3000
    volumes: 
      - .:/app/
    depends_on: 
      - database
    environment: 
      HOST: 0.0.0.0
      MONGODB_HOST: database

  database:
    image: bitnami/mongodb:latest
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes