version: '3'

volumes:
  mongodb_data:
    driver: local

services:
  nginx:
    image: nginx:1.18.0-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    
  app:
    image: docker.pkg.github.com/dylanblokhuis/twitch-emotes-warehouse/app:latest
    volumes: 
      - .:/app/
    depends_on: 
      - database
    environment: 
      HOST: 0.0.0.0
      MONGODB_HOST: database

  database:
    image: bitnami/mongodb:latest
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes