name: Deploy Code to VPS
on: push
jobs:
  push_package:
    name: Push Docker image to Github Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login https://docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker Build
        run: |
          docker build -t docker.pkg.github.com/dylanblokhuis/twitch-emotes-warehouse/app:latest .
      - name: Docker Push
        run: |
          docker push docker.pkg.github.com/dylanblokhuis/twitch-emotes-warehouse/app:latest
  build:
    needs: push_package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "~/twitch-emotes-warehouse"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: cd ~/twitch-emotes-warehouse && docker-compose -f docker-compose.production.yml up -d